In [2]:
import csv


with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3] # The first three dictionaries in our list.

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [3]:
HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # if the cylinder amount type matches,
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

NameError: name 'vehicleclass' is not defined

# time and date

In [ ]:
import time as tm
import datetime as dt
tm.time()

In [ ]:
tm.localtime()

In [ ]:
delta=dt.timedelta(days=50)
delta

In [ ]:
day=dt.date.today()
day

In [ ]:
day-delta

In [ ]:
day+delta

# The Python Programming Language: Objects and map()

## An example of a class in python:

In [ ]:
class Employee:
    department='income tax'
def set_name(self,new_name):
    self.name=new_name
def set_location(self,new_location):
    self.location=new_location

In [ ]:
employee=Employee()
employee.set_name=('archana')
employee.set_location=('vijayawada')
print('{} live in  {} vij {}'.format(employee.name,employee.location,employee.department))
    

In [ ]:
s1=[1,2,3,4,5]
s2=[5,4,6,7,8]
s=list(map(min,s1,s2))
print(s)

# list 

In [ ]:
s1="abcd"
s2="4512"
s=[(c1+c2+n1+n2) for c1 in s1 for c2 in s1 for n1 in s2 for n2 in s2]
print(s)

## numpy


In [ ]:
import numpy as np
a=np.array([1,2,3])
a
a.shape

In [ ]:
import numpy as np
a=np.array([[1,2,3],[5,4,3]])
print(a)
a.shape

In [ ]:
import numpy as np
a=np.random.randint(0,9,size=(3,3))
a

In [ ]:
import numpy as np
a=np.arange(0,9)
a
a.reshape(3,3)

In [ ]:
import numpy as np
a=np.linspace(0,6,10)
a


In [ ]:
import numpy as np
a=np.ones((3,4),int)
a

In [ ]:
import numpy as np
a=np.zeros((3,4),int)
a

In [ ]:
np.eye(3)

In [ ]:
x=[1,2,3]
a=np.diag(x)
a

In [ ]:
import numpy as np
a=np.arange(0,9)
a
a.reshape(3,3)

In [ ]:
a=np.array([1,2,3])
a

In [ ]:
b=np.array([4,3,2])
b

In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

In [ ]:
a

In [ ]:
x=np.array([1,2,3])
x

In [ ]:
y=np.array([5,4,3])
y

In [ ]:
x.dot(y)

In [ ]:
a=np.random.randint(0,9,size=(3,2))
a
a.T

In [ ]:
a

In [ ]:
a.min()
a.max()
a.sum()

In [ ]:
a.std()

In [6]:
import numpy as np
A=np.arange(12)**2
A

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [7]:
A[-4]

64

In [8]:
A[0:5:2]

array([ 0,  4, 16], dtype=int32)

In [15]:
A=np.arange(12)
A.resize(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
A[2,2]

8